version: "3"

services:
  citylist:
    container_name: citylist
    build: .
    image: alexandergock/citylist:0.0.1
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres:5432/citylist
      - spring.datasource.username=citylist
      - spring.datasource.password=postgres

  postgres:
    container_name: postgres
    image: postgres:15.1
    environment:
      - POSTGRES_USER=citylist
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=citylist
    volumes:
      - citylist-postgres:/var/lib/postgresql/data

volumes:
  citylist-postgres:
    external: false
